### ISSUE TITLE
Remove hardcode 'argocd` namespace from installation manifests

### ISSUE THREAD

**Issue by alexmt** [argoproj-labs/appsource#39]
AppSource typically going to be installed into it's own namespace in managed cluster (as opposed to controller plane cluster which host Argo CD). In order to simplify installation the resources defined https://github.com/argoproj-labs/appsource/blob/master/manifests/install.yaml should not have any namespace.

**Comment by aceamarco** [comment]
That's fair, I'll go ahead and change the kustomization manifests.
